### PR TITLE
update deps, update generation code, generate clientset

### PR DESCRIPTION
**Pull request by maya-r**

### CODE REVIEW

**Comment by awels** [comment]
So question, is all this so that make generate works against the node placement from kubernetes?

**Comment by maya-r** [comment]
only to generate the clientset. it was my first working attempt, I can try to reduce the set of changes.

**Comment by maya-r** [comment]
to be more verbose, it is so I can write [this code](https://github.com/kubevirt/hostpath-provisioner/pull/57/files#diff-88005ee7fb0ad58ac516e4996225ecc1ec512ccdef5fec3819c25db909fad259R79-R87). Without a generated client, I can't.

**Comment by awels** [comment]
Gotcha, since your test needs to modify the CR, and you need the client for that.

**Review by awels — APPROVED** [review]

**Pull request merged**
